### ISSUE TITLE
Self Hosting Kumu on a Linux Server with Docker

### ISSUE THREAD

**Issue by MetaBliss** [kumu/docs#27]
Hi there, I was wondering if you have kumu available as a docker container to install with docker compose?

I have a linux based server and would love to spin up a self-hosted instance of Kumu with Docker Compose. I would be using it for university research however as a graduate student my funds are very tight and I deal with sensitive data in the security and defense realm so I need to self host it internally with the ability to share with my Professor and Dean.

**Comment by danprince** [comment]
Hi @MetaBliss, the only self-hosting option is our [Enterprise offering](https://kumu.io/enterprise) which runs in a virtual machine. We don't provide a version of enterprise that runs in Docker.

If you are working with sensitive data on a budget then it's more likely that you'd have success using a [remote blueprint](https://docs.kumu.io/guides/blueprints#set-a-remote-blueprint) hosted on your own server on an internal network.

Feel free to reach out to support@kumu.io if you want to ask more questions, so that we can keep this repo for questions relating to our docs.

Thanks!
